FROM php:8.1-apache

# 必要なパッケージとPHP拡張モジュールをインストール
RUN apt-get update && apt-get install -y \
    locales \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    iputils-ping \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd mysqli

# ロケールの設定
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

# Apacheの設定
RUN a2enmod rewrite

# 作業ディレクトリの設定
WORKDIR /var/www/html

# プロジェクトファイルをコピー
COPY . /var/www/html/

# パーミッションの設定
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html
