version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - fuelphp-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fuelphp
      MYSQL_USER: fuelphp_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - fuelphp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - fuelphp-network

networks:
  fuelphp-network:
    driver: bridge
